spring:
  jmx:
     default-domain: suite2
  application:
     name: suite-service  # Service registers under this name
  datasource:
     url: jdbc:mysql://localhost:3306/suite2_all_antiguo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Lima&enabledTLSProtocols=TLSv1.2
     username: root
     password: root
     testOnBorrow: true
     validationQuery: select 1
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        proc:
            param_null_passing: true

server:
  port: 8092   # HTTP (Tomcat) port
  compression:
      enabled: true
      mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
logging:
  level:
    org.exampledriven.eureka: DEBUG